workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 20
      java: 17
      groups:
        - supabase_credentials
      vars:
        VITE_SUPABASE_URL: https://ynahfciaixjjgzbbmjuf.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InluYWhmY2lhaXhqamd6YmJtanVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNjg1NTMsImV4cCI6MjA4MDY0NDU1M30.ORS6iroFT-A2TuMU9TZyCMuuSZBieTDKeivIjlixjMI
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
